=== Shubhada-24/HARRY_26/XML&XSD/PS12-Shop-Inventory/shop.xsd
<?xml version="1.0"?>

<xs:schema
xmlns:xs="http://www.w3.org/2001/XMLSchema">


    <xs:element name="Inventory">

        <xs:complexType>

            <xs:sequence>


                <xs:element

                name="Product"

                minOccurs="1"

                maxOccurs="unbounded">


                    <xs:complexType>

                        <xs:sequence>


                            <xs:element
                            name="ProductID"
                            type="xs:integer"/>


                            <xs:element
                            name="Name"
                            type="xs:string"/>



                            <xs:element
                            name="Category">

                                <xs:simpleType>

                                    <xs:restriction
                                    base="xs:string">

                                        <xs:enumeration
                                        value="Electronics"/>

                                        <xs:enumeration
                                        value="Clothing"/>

                                        <xs:enumeration
                                        value="Food"/>

                                    </xs:restriction>

                                </xs:simpleType>

                            </xs:element>



                            <xs:element
                            name="Stock">

                                <xs:simpleType>

                                    <xs:restriction
                                    base="xs:integer">

                                        <xs:minInclusive
                                        value="0"/>

                                    </xs:restriction>

                                </xs:simpleType>

                            </xs:element>



                            <xs:element
                            name="Price"
                            type="xs:decimal"/>


                        </xs:sequence>

                    </xs:complexType>

                </xs:element>


            </xs:sequence>

        </xs:complexType>

    </xs:element>

</xs:schema>

=== Shubhada-24/HARRY_26/XML&XSD/PS12-Shop-Inventory/shop.xml
<?xml version="1.0"?>

<Inventory
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="shop.xsd">


    <Product>

        <ProductID>1</ProductID>

        <Name>Laptop</Name>

        <Category>Electronics</Category>

        <Stock>10</Stock>

        <Price>65000.00</Price>

    </Product>



    <Product>

        <ProductID>2</ProductID>

        <Name>T-Shirt</Name>

        <Category>Clothing</Category>

        <Stock>25</Stock>

        <Price>799.50</Price>

    </Product>



    <Product>

        <ProductID>3</ProductID>

        <Name>Chocolate</Name>

        <Category>Food</Category>

        <Stock>50</Stock>

        <Price>120.00</Price>

    </Product>



    <Product>

        <ProductID>4</ProductID>

        <Name>Mobile</Name>

        <Category>Electronics</Category>

        <Stock>15</Stock>

        <Price>30000.00</Price>

    </Product>



    <Product>

        <ProductID>5</ProductID>

        <Name>Jeans</Name>

        <Category>Clothing</Category>

        <Stock>12</Stock>

        <Price>1500.00</Price>

    </Product>


</Inventory>
